### ISSUE TITLE
MemeDetail Page

### ISSUE THREAD

**Issue by seunghyukcho** [gimme1dollar/conceptual-excel-map-viewer#8]
Meme의 정보를 확인할 수 있는 페이지는, tab들로 구현할 예정
- https://vuetifyjs.com/ko/components/tabs/
- 왼쪽 목차는 detail의 category 목록
- 각 category의 detail들은 summary를 소제목, description을 내용으로 나열할 예정

**Comment by gimme1dollar** [comment]
현재 (home)/meme/(숫자) 로 page를 구분하고 있는데, 이를 (home)/meme/(meme이름) 으로 페이지 구분 하도록 변경 요청.

**Comment by gimme1dollar** [comment]
nav bar에 main 설명이 현재는 meme페이지에서도 cross로 고정돼있는데, 이를 meme 이름으로 변경할 것 요청.

**Comment by gimme1dollar** [comment]
* 모바일용 가독성 위해 독립적인 디자인 필요

**Comment by seunghyukcho** [comment]
- [ ] URL 수정(/meme/<id:int> => /meme/<name:str>)
- [ ] Nav bar 타이틀이 Meme에 따라 바뀌게 수정(현재는 Cross로 고정되어 있음)
